# Generated by Django 3.1.7 on 2021-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalkwayLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('time_required', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('point_number', models.IntegerField()),
                ('point_name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'WalkwayLocation',
            },
        ),
    ]
